#!/usr/bin/env python3
"""Build the public JSON API payload: dist/api/v1/roster.json.

Read-only, no query parameters, no authentication. The file is regenerated by
gen.py on every run so it can never drift from data/models.json, and it carries
the benchmark index written by bench.py.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bench
from snapshot import load_snapshot
from sources.common import PROVIDER_BASE_URLS

SCHEMA_VERSION = 1
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dist", "api", "v1", "roster.json")

# Public field names, in payload order. The raw Artificial Analysis field names
# are implementation detail of the upstream dataset.
BENCH_FIELDS = (
    ("intelligence_index", "artificial_analysis_intelligence_index"),
    ("coding_index", "artificial_analysis_coding_index"),
    ("agentic_terminal", "terminalbench_hard"),
    ("gpqa", "gpqa"),
    ("output_tokens_per_second", "median_output_tokens_per_second"),
    ("time_to_first_token_seconds", "median_time_to_first_token_seconds"),
)


def build_endpoints(model):
    """One callable OpenAI-compatible endpoint per source that lists the model.

    The per-source id is required, not cosmetic: providers prefix ids
    differently (`inclusionai/ling-3.0-flash-fin` on OpenRouter vs
    `ling-3.0-flash-fin:free` on Nous Portal), so the normalized roster id is
    not always callable.
    """
    source_ids = model.get("source_ids") or {}
    endpoints = []
    for source in model.get("sources", []):
        base_url = PROVIDER_BASE_URLS.get(source)
        if not base_url:
            continue
        endpoints.append({
            "provider": source,
            "base_url": base_url,
            "model_id": source_ids.get(source) or model.get("display_id") or model["id"],
        })
    return endpoints


def build_benchmarks(model, index):
    record = (index or {}).get(model["id"]) or {}
    result = {
        "source": "artificial-analysis",
        "matched": bool(record.get("aa_matched")),
        "aa_name": record.get("aa_name", ""),
        "paid_proxy": bool(record.get("paid_proxy")),
        "excluded": bool(record.get("excluded")),
    }
    for public, raw in BENCH_FIELDS:
        result[public] = record.get(raw)
    return result


def build_model(model, index):
    return {
        "id": model["id"],
        "display_id": model.get("display_id") or model["id"],
        "name": model.get("name") or model["id"],
        "description": model.get("description", ""),
        "free_basis": model.get("free_basis", ""),
        "sources": list(model.get("sources", [])),
        "context_length": model.get("context_length"),
        "modalities": model.get("modalities", ""),
        "tools": bool(model.get("tools")),
        "endpoints": build_endpoints(model),
        "benchmarks": build_benchmarks(model, index),
    }


def build_payload(snapshot, index):
    models = snapshot.get("models") or []
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": snapshot.get("generated_at", ""),
        "counts": {
            "models": len(models),
            "sources": len(snapshot.get("statuses") or {}),
        },
        "sources": snapshot.get("statuses") or {},
        "models": [build_model(m, index) for m in models],
    }


def write(payload, path=OUT):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=1)
        f.write("\n")
    os.replace(tmp, path)
    return path


def main():
    snapshot = load_snapshot()
    if not snapshot:
        raise SystemExit("api: no data/models.json snapshot to publish")
    index = bench.load_index()
    payload = build_payload(snapshot, index)
    write(payload)
    matched = sum(1 for m in payload["models"] if m["benchmarks"]["matched"])
    print(f"api roster.json written: {payload['counts']['models']} models, "
          f"{matched} benchmark-matched, benchmark index "
          f"{'present' if index else 'missing'}")


if __name__ == "__main__":
    main()
