#!/usr/bin/env python3
"""Render the GitHub-facing README.md from data/models.json + data/history.json.

Runs inside the existing model-wiki pipeline, after snapshot.py has written the
roster. Reads the narrative shell from readme.template.md and substitutes the
generated table, source list, and recent-change summary. Anything the template
marks as EXTRA (below the generated marker) is preserved verbatim from the
previous README, so hand-written notes survive regeneration.

Writes to a target directory (default: the sibling free-llm-roster checkout)
rather than this repository, because the public-facing repo is separate from
the automation repo.
"""

from datetime import datetime, timezone
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
TEMPLATE = os.path.join(HERE, "readme.template.md")
DEFAULT_TARGET = "/opt/free-llm-roster"

MARKER = "<!-- GENERATED BY readme.py"
EXTRA_OPEN = "{{EXTRA}}"

SOURCE_LABELS = {
    "openrouter": "OpenRouter",
    "nous": "Nous Portal",
    "opencode-zen": "OpenCode Zen",
}
SOURCE_NOTES = {
    "openrouter": "aggregated free tiers, `:free` variant",
    "nous": "direct from Nous Research",
    "opencode-zen": "curated gateway, some contributor-gated",
}

# Cheap-to-read, stable ordering. Keep in sync with gen.py USE_CASES.
USE_CASES = [
    ("Deep reasoning / research", ["reasoning", "ultra", "thinking", "r1", "nemotron-3-ultra"]),
    ("Agentic coding", ["cod", "laguna", "devstral"]),
    ("Long-context work", ["longcat"]),
    ("Vision / multimodal", ["vision", "omni", "vl-", "-vl", "gemma"]),
    ("Fast / lightweight", ["lightning", "flash", "nano", "mini", "lfm"]),
    ("General purpose fallback", []),
]


def load(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def esc(text):
    """Escape pipes and collapse newlines so a value cannot break a table row."""
    return str(text or "").replace("|", "\\|").replace("\n", " ").strip()


def assign_role(model):
    hay = (model["id"] + " " + (model.get("description") or "")[:200]).lower()
    for role, keywords in USE_CASES:
        if any(keyword in hay for keyword in keywords):
            return role
    return USE_CASES[-1][0]


def sort_models(models):
    order = {role: index for index, (role, _) in enumerate(USE_CASES)}
    source_order = {"nous": 0, "opencode-zen": 1, "openrouter": 2}

    def primary_source(model):
        return min(source_order.get(source, 9) for source in model.get("sources", []))

    return sorted(models, key=lambda m: (order.get(m.get("role"), 99),
                                         primary_source(m),
                                         (m.get("name") or m["id"]).lower()))


def fmt_context(value):
    if not value:
        return "—"
    return f"{int(value) // 1000}k" if value >= 1000 else str(value)


def render_table(models):
    rows = ["| Model | Name | Context | Modalities | Tools | Free via |",
            "| --- | --- | --- | --- | --- | --- |"]
    for model in sort_models(models):
        sources = ", ".join(SOURCE_LABELS.get(s, s) for s in model.get("sources", []))
        # Only link to OpenRouter when the model is actually served there; Zen-only
        # and Nous-only ids are not valid OpenRouter slugs.
        if "openrouter" in model.get("sources", []):
            name_cell = f"[`{esc(model['id'])}`](https://openrouter.ai/{esc(model['id'])})"
        else:
            name_cell = f"`{esc(model['id'])}`"
        rows.append(
            f"| {name_cell} "
            f"| {esc(model.get('name'))} "
            f"| {fmt_context(model.get('context_length'))} "
            f"| {esc(model.get('modalities')) or '—'} "
            f"| {'yes' if model.get('tools') else '—'} "
            f"| {esc(sources)} |")
    return "\n".join(rows)


def render_sources(models):
    seen = {source: 0 for source in SOURCE_LABELS}
    for model in models:
        for source in model.get("sources", []):
            seen[source] = seen.get(source, 0) + 1
    lines = ["| Source | Models | What counts as free |", "| --- | --- | --- |"]
    for source, label in SOURCE_LABELS.items():
        lines.append(f"| {label} | {seen.get(source, 0)} | {SOURCE_NOTES[source]} |")
    return "\n".join(lines)


def render_changes(history, limit=8):
    if not history:
        return "_No recorded changes yet._"
    lines = []
    for entry in history[-limit:][::-1]:
        stamp = (entry.get("at") or "")[:10]
        parts = []
        if entry.get("added"):
            parts.append(f"**+{len(entry['added'])}** added")
        if entry.get("removed"):
            parts.append(f"**−{len(entry['removed'])}** removed")
        if not parts:
            continue
        lines.append(f"- `{stamp}` — " + ", ".join(parts))
    if not lines:
        return "_No changes in the recorded window._"
    return "\n".join(lines)


def human_stamp(iso):
    try:
        moment = datetime.strptime(iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return iso or "unknown"
    return moment.strftime("%Y-%m-%d %H:%M UTC")


def extract_previous_extra(existing_text):
    """Pull the hand-written tail out of the README we are about to overwrite."""
    if not existing_text:
        return ""
    match = re.search(re.escape(MARKER) + r"[^\n]*\n(.*)$", existing_text, re.S)
    if not match:
        return ""
    return match.group(1).replace(EXTRA_OPEN, "").strip()


def build(models_doc, history, extra, template):
    models = [dict(m, role=assign_role(m)) for m in models_doc.get("models", [])]
    generated = models_doc.get("generated_at", "")
    # Count sources that actually contributed a model, not fetch successes: a source
    # can be reachable and still yield nothing, and a degraded fetch should not
    # shrink the number the README advertises.
    live_sources = {s for m in models for s in m.get("sources", [])}
    source_count = len(live_sources)

    values = {
        "{{MODEL_COUNT}}": str(len(models)),
        "{{SOURCE_COUNT}}": str(source_count),
        "{{DATE_SHORT}}": (generated or "")[:10] or "n/a",
        "{{GENERATED_HUMAN}}": human_stamp(generated),
        "{{TABLE}}": render_table(models),
        "{{SOURCES}}": render_sources(models),
        "{{CHANGES}}": render_changes(history),
        "{{EXTRA}}": extra,
    }
    out = template
    for key, value in values.items():
        out = out.replace(key, value)
    return out


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("README_TARGET", DEFAULT_TARGET)
    os.makedirs(target, exist_ok=True)
    out_path = os.path.join(target, "README.md")

    models_doc = load(os.path.join(DATA_DIR, "models.json"))
    history_path = os.path.join(DATA_DIR, "history.json")
    history = load(history_path) if os.path.exists(history_path) else []
    with open(TEMPLATE, encoding="utf-8") as handle:
        template = handle.read()

    previous = None
    if os.path.exists(out_path):
        with open(out_path, encoding="utf-8") as handle:
            previous = handle.read()

    rendered = build(models_doc, history, extract_previous_extra(previous), template)
    if previous == rendered:
        print("README unchanged")
        return

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"README written: {out_path} ({len(models_doc.get('models', []))} models)")


if __name__ == "__main__":
    main()
