#!/usr/bin/env bash
# Regenerate the Cloudflare range files from Cloudflare's published lists.
#
# Runs on the VPS. Two files are produced from one fetch, because the origin
# lock and the real-IP trust must never disagree about who is trusted:
#
#   /etc/nginx/conf.d/cloudflare-realip.conf   set_real_ip_from  (rate limits)
#   /etc/nginx/snippets/cloudflare-ranges-only.conf   allow      (standalone)
#   /etc/nginx/conf.d/cloudflare-origin-lock-geo.conf   geo      (origin lock)
#
# WHY THIS NEEDS TO BE RUNNABLE: the allowlist fails CLOSED. If Cloudflare adds
# an edge range and this has not been re-run, legitimate visitors are refused
# until it is. That is the right trade (visible breakage over silent exposure),
# but it means the list must be maintainable without me.
#
# Add it to cron if you want the lock to survive Cloudflare network changes:
#   17 4 * * *  bash /opt/model-wiki-automation/deploy/update-cloudflare-ranges.sh
# The script reloads nginx only when the content actually changed.
set -euo pipefail

REALIP=/etc/nginx/conf.d/cloudflare-realip.conf
ALLOW=/etc/nginx/snippets/cloudflare-ranges-only.conf
# conf.d, not snippets: `geo` is only valid in the http context, and conf.d is
# included there. A file that sits in snippets/ looks right and is never loaded.
LOCKMAP=/etc/nginx/conf.d/cloudflare-origin-lock-geo.conf

fetch() {
  curl -sSf --max-time 30 "$1" | tr -d '\r' | grep -E "^[0-9a-fA-F:.]+/[0-9]+$"
}

V4=$(fetch https://www.cloudflare.com/ips-v4 || true)
V6=$(fetch https://www.cloudflare.com/ips-v6 || true)

if [ -z "$V4" ] && [ -z "$V6" ]; then
  echo "ERROR: could not fetch Cloudflare ranges; leaving the current config untouched" >&2
  echo "Refusing to write an empty allowlist: that would lock out every visitor." >&2
  exit 1
fi

# An empty result for one family is suspicious but not fatal; refuse only when
# both are empty. Losing IPv6 trust would break IPv6 visitors, so warn loudly.
if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "WARNING: only one address family returned (v4=${#V4} lines, v6=${#V6} lines)." >&2
  echo "Writing it anyway, but check https://www.cloudflare.com/ips/ by hand." >&2
fi

ALL=$(printf '%s\n%s\n' "$V4" "$V6" | sed '/^$/d' | sort -u)

TMP_REALIP=$(mktemp)
TMP_ALLOW=$(mktemp)
TMP_LOCKMAP=$(mktemp)
trap 'rm -f "$TMP_REALIP" "$TMP_ALLOW" "$TMP_LOCKMAP"' EXIT

{
  # No timestamp in any of the three headers: `cmp` below compares
  # byte-for-byte, and a date would make every run look like a change and
  # reload nginx for no reason.
  echo "# Cloudflare published ranges (ips-v4 + ips-v6)."
  echo "# Generated by deploy/update-cloudflare-ranges.sh -- do not hand-edit."
  echo "# $(echo "$ALL" | wc -l) ranges. Both the origin allowlist and the real-IP trust"
  echo "# are generated from this single fetch so they cannot drift apart."
  echo "#"
  echo "# CF-Connecting-IP is only believed for these sources. Without this,"
  echo "# \$remote_addr is the Cloudflare edge and the API rate limit counts every"
  echo "# visitor as one address."
  echo "real_ip_header CF-Connecting-IP;"
  echo "$ALL" | sed 's|^|set_real_ip_from |; s|$|;|'
} > "$TMP_REALIP"

{
  echo "# Cloudflare's published edge ranges, for use as an nginx allow list."
  echo "# Generated by deploy/update-cloudflare-ranges.sh -- do not hand-edit."
  echo "# Used as an allowlist so the origin refuses traffic that bypasses Cloudflare."
  echo "# Allowlist, not denylist: an unknown address is refused, and a new"
  echo "# Cloudflare range shows up as visible breakage until this is re-run."
  echo "$ALL" | sed 's|^|allow |; s|$|;|'
} > "$TMP_ALLOW"

# The origin-lock classification. `geo`, not `map`: a map block matches EXACT
# values only, so keyed on an address it never matches 172.69.155.12 against the
# entry 172.64.0.0/13 and every real Cloudflare edge falls to `default 0` --
# which is how the first attempt at this lock 403'd the entire internet.
# Keyed on $realip_remote_addr (the Cloudflare edge, captured before
# real_ip_header rewrites $remote_addr to the visitor). `default 0` fails closed.
{
  # No timestamp in this header: `cmp` below compares byte-for-byte, and a date
  # would make every run look like a change and reload nginx for no reason.
  echo "# Origin-lock classification for llmroster.dev's origin."
  echo "# Generated by deploy/update-cloudflare-ranges.sh -- do not hand-edit."
  echo "# Tests \$realip_remote_addr (the Cloudflare edge), NOT \$remote_addr"
  echo "# (the visitor, after the real_ip_header rewrite)."
  echo "geo \$realip_remote_addr \$origin_lock_allowed {"
  echo "    default 0;"
  # geo requires a prefix length; a bare host address is a syntax error.
  echo "    127.0.0.1/32 1;"
  echo "    ::1/128     1;"
  echo "$ALL" | sed 's|^|    |; s|$| 1;|'
  echo "}"
} > "$TMP_LOCKMAP"

changed=0
for pair in "$TMP_REALIP:$REALIP" "$TMP_ALLOW:$ALLOW" "$TMP_LOCKMAP:$LOCKMAP"; do
  new="${pair%%:*}"; target="${pair##*:}"
  mkdir -p "$(dirname "$target")"
  if [ ! -f "$target" ] || ! cmp -s "$new" "$target"; then
    if [ -f "$target" ]; then cp "$target" "$target.bak-$(date -u +%Y%m%dT%H%M%SZ)"; fi
    cp "$new" "$target"
    chmod 0644 "$target"
    echo "updated $target"
    changed=1
  fi
done

if [ "$changed" = "0" ]; then
  echo "no change (ranges current)"
  exit 0
fi

nginx -t
systemctl reload nginx
echo "nginx reloaded with updated Cloudflare ranges"